---
server:
  port: 8800
  error:
    include-message: always

spring:
  application:
    name: Bookommerce-Backend
  profiles:
    active: pgsql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create


logging:
  level:
    root: INFO
---

---

### PgSQL profile

spring:
  profiles: pgsql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/buggieDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}

---
